name: benchmark

on:
  push:

jobs:
  benchmark:
    timeout-minutes: 10
    if: github.repository == 'open-coap/java-coap'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build
        run: ./gradlew jmhJar
      - name: Run benchmarks
        run: ./gradlew jmh
      - name: print summary
        run: |
          echo '### JMH report' >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          find . -path '*/results/jmh/*.txt' -type f | xargs cat >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
